---
- name: Install comman package 
  become: yes
  hosts: all 
  gather_facts: yes
  roles:
   - common

- name: Install the web server 
  become: yes
  hosts: web-server
  gather_facts: no 
  roles:
   - web-server

- name: Install and configure the database
  gather_facts: yes
  become: true
  hosts: db-servers
  roles:
    - db-server     
     
